# Generated by Django 4.2.4 on 2024-08-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
