# Generated by Django 4.2.4 on 2024-09-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0004_remove_products_price_productitem_products_items"),
        ("orders", "0002_order_address_order_city_order_mobile_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admin_settings.productitem",
            ),
        ),
        migrations.AddField(
            model_name="orderproductamount",
            name="product_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admin_settings.productitem",
            ),
        ),
    ]
