# Generated by Django 4.2.4 on 2024-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_cart_product_item_orderproductamount_product_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproductamount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
