# Generated by Django 4.2.4 on 2024-07-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0002_productimages_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
    ]
