# Generated by Django 4.2.4 on 2024-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0004_remove_products_price_productitem_products_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productitem",
            name="name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
