# Generated by Django 4.2.4 on 2024-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0005_remove_productitem_quantity_productitem_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
